### ISSUE TITLE
UI breakage on terminal font size changed

### ISSUE THREAD

**Issue by Piturnah** [DCoxshall/dyledit#1]
When the terminal font size changes, e.g. I want to zoom in and out, the application breaks in that the rendering is not updated to reflect it. 

e.g. oops
![image](https://github.com/DCoxshall/dyledit/assets/20472367/70447a7c-3890-47b5-9d46-c31648ca02b9)

I had a quick go resolving the issue this way:

```diff
diff --git a/editor.py b/editor.py
index 0c5db51..5259b96 100644
--- a/editor.py
+++ b/editor.py
@@ -497,6 +497,9 @@ class Editor:
         exit(0)
 
     def refreshScreen(self):
+        self.screenrows = os.get_terminal_size().lines - 2
+        self.screencols = os.get_terminal_size().columns
+
         self.scroll()
 
         self.buffer = ""
```

This patch *mostly* works for font size *decreases*, except that the redraw occurs only after the next input event

For font size increases, it causes an additional issue which is unexpected behaviour on the very next navigation input

Would've dug into it a bit deeper but I'm unfortunately extremely tired this evening. This is a very cool project by the way, whether or not you plan to go further with it!

## Environment

OS: NixOS 23.05
Terminal: Kitty v0.28.1

**Comment by Piturnah** [comment]
By the way - most terminals provide an API for reading resize events (which is what happens when the font size changes)

**Comment by DCoxshall** [comment]
I've taken a look over this, and tried your patch, and it seems to just work. After altering `refreshScreen()` like you've suggested, I can't get the editor to break, after testing on terminator, gnome-terminal, and alacritty, and kitty. Might be an issue with NixOS? I don't know enough about it to say. I'm probably going to close this unless you have anything else to add.
I also found and fixed another (unrelated) bug in the search function while trying this out, so that's nice. 
Thank you for the support, I really appreciate it :)

**Comment by Piturnah** [comment]
That's very interesting, I did not expect this bug to be environment specific - I tried explicitly flushing stdout after the screen refresh and had no effect

It's very surprising to me that you can't reproduce the bug. Is it reproducible *before* applying the patch I showed? I would get a screen recording for you of the behaviour but my internet has been down all day

To be a bit more clear, I am talking about the behaviour upon pressing (by default) `Ctrl-Shift-+` and `Ctrl-Shift--` on Kitty

I tested on Alacritty as well and saw the same issue

I'll have a further look when I get the chance

**Comment by Piturnah** [comment]
Upon further investigation I figured out the problem was because after a resize the editor effectively does nothing until the next keypress

This is because it is blocking on the first line of `readKey`

I have a solution to this using curses (it's just a wrapper around ncurses) which is included with the standard python distribution

Curses provides a function `getch` that blocks and gets a terminal input, like `stdin.read`, but it also unblocks and returns a code if it gets other terminal events like a resize

I can open a PR for this if it seems like a reasonable solution to you. One thing worth considering is that curses provides many other terminal APIs that are useful, and things such as constants for ANSI escapes, so it might make sense to port more parts of the code to curses APIs as well if you are going to import it anyway.

I can open a minimal PR with just the fix to this issue and we can see where to go from there?

Alternatively we can look for a lower level API to handle the resize event, but I think this method will necessarily involve multithreading* as the `stdin.read` and the resize event read API are both blocking. Curses seems more convient to me.

*Edit: could also do this by spinning but I'm assuming you value your CPU cycles at least a little bit 😅

**Comment by DCoxshall** [comment]
> which is included in the standard python distribution

I cannot believe I didn't know this. I always assumed that curses was an external library. I've never done serious python development under Linux before, so I've never looked seriously at curses. At first glance I thought "I'd rather not use an external library", but - not to be dramatic - this changes everything. I can't believe I've done this entire project without knowing curses was part of python's standard distribution.

Can you give me a few days to just check curses out properly? If curses is available in python's libraries by default I might even do a massive rewrite using curses (although that might not be necessary). Open a PR if you like, but I probably won't merge anything until I have a usable understanding of curses. 

And about the bug: I think what you thought was a bug was actually expected (albeit kind of shitty) behaviour. We're talking about the editor only properly expanding to fill the screen after another keypress, right? And I think on kitty the terminal just goes blank (I assume this is due to kitty being written using OpenGL). I expected that to happen, as it's the same behaviour present in the original Kilo editor by antirez. I wasn't planning on fixing this to be honest, but if it's as simple as just bringing in curses an changing a few lines then I'd definitely look into it.

**Comment by DCoxshall** [comment]
I've just written a small fix which (I believe) should clear up any issues to do with resizing the terminal or changing the font size, without using curses. It works by polling for input with a timeout, so if there's no input within a given time, the screen resizes itself.
